# Generated by Django 5.1.1 on 2024-09-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_item_vote_ratio_item_vote_total_review_item_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='projects',
        ),
    ]
