# Generated by Django 5.1.1 on 2024-10-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_item_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
